# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160125_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='platform',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
