# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160127_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='display_color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
